name: progress_dialog
description: A light weight library to easily manage a progress dialog with simple steps whenever you need to do it. You can easily show and hide it.
version: 1.2.16
#author: Fayaz<fayazfz07@gmail.com>
homepage: https://github.com/fayaz07/progress_dialog

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rflutter_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/double_ring_loading_io.gif

